version: '3.8'

services:
  app:
    image: node:14.15.1-alpine
    working_dir: '/app'
    env_file: './.env'
    ports:
      - '2309:2309'
    volumes:
      - './app:/app'
      - 'app_modules:/app/node_modules'
    command: 
      - '/bin/ash'
      - '-c'
      - 'npm i && npm run dev'
    depends_on:
      - server

  server:
    image: node:14.15.1-alpine
    working_dir: '/server'
    ports:
      - '4242:4242'
    volumes:
      - './server:/server'
      - 'server_modules:/server/node_modules'
    command: 
      - '/bin/ash'
      - '-c'
      - 'npm i && npm run dev'

volumes: 
  app_modules:
  server_modules:
